suggested structure with demo files, add linting
ourjapanlife/findadoc-news pull request #1
Opened 2021-07-24 23:12 UTC by ann-kilzer

- [x] Create a demo blogpost with suggested file format and structure
- [ ] Add linting for Markdown

2021-07-25 00:41 UTC, ermish commented on package.json
> +  "license": "UNLICENSED",
should have a license since open source

2021-07-25 00:45 UTC, ermish commented on package.json
> +    "prepare": "husky install"
It looks like `prepare` should actually be `postinstall` according to their [docs](https://typicode.github.io/husky/#/?id=yarn-2)? You're more familiar with husky though, so this might not be the case 🤷‍♂️

2021-07-25 00:46 UTC, ermish commented on .github/CODEOWNERS
> +* @theyokohamalife @ann-kilzer @Ermish
super small nit: @ermish is lowercased

2021-07-25 02:27 UTC, theyokohamalife reviewed
Since the name of the file will become part of the URL I think we should use dashes if we'll include the dates. Ex. `/2021-07-25/my-cool-news-en.md`

2021-07-25 03:48 UTC, theyokohamalife commented on package.json
> +  "license": "UNLICENSED",
I just added a license to the repo so we'll probably need to update the `package.json`

2021-07-25 05:18 UTC, ann-kilzer commented on .github/CODEOWNERS
> +* @theyokohamalife @ann-kilzer @Ermish
Ahh it a direct copy from the other repo

2021-07-25 05:19 UTC, ann-kilzer commented on package.json
> +  "license": "UNLICENSED",
This was intentional... do we want the written content to be open source? I feel like it's categorically different

2021-07-25 05:20 UTC, ann-kilzer commented on package.json
> +    "prepare": "husky install"
That's only for Yarn 2. AFAIK we are using yarn 1? The other repos are this way

2021-07-25 05:22 UTC, theyokohamalife commented on package.json
> +  "license": "UNLICENSED",
I'm open to suggestions! I just copied the license from the other repo.

2021-07-25 05:23 UTC, ermish commented on .github/CODEOWNERS
> +* @theyokohamalife @ann-kilzer @Ermish
yeah, I noticed that one was incorrect as well but didn't bother to mention :)

2021-07-25 05:24 UTC, ann-kilzer commented
The file structure doesn't have to become part of the url. We can write anything we desire in the plug-in. I'm okay with any separator.

2021-07-25 05:28 UTC, ermish commented on package.json
> +    "prepare": "husky install"
oh snap! I thought I was using YARN 2, but it's 1.22.
n/m! fine as is.

2021-07-25 05:34 UTC, ermish commented on package.json
> +  "license": "UNLICENSED",
I think there's some pros/cons. 
personally, I would make this a private repo since the public won't be contributing really. And any additional authors that do, we can just provide access. 
Public is fine as well, but we should definitely have some sort of license then.

2021-07-25 06:38 UTC, ann-kilzer commented on package.json
> +  "license": "UNLICENSED",
We may have different translators from the public, but we may want to retain IP for the written content. I would recommend removing any other license until we reach a decision. Better to restrict it and loosen than the other way around

2021-08-22 02:31 UTC, theyokohamalife approved these changes
LGTM after some small changes mentioned by @ermish

2021-08-22 04:38 UTC, theyokohamalife requested changes

2021-08-22 04:38 UTC, theyokohamalife commented on 2021.07.25.My-Cool-News-Story/en.md
> +# Hello, World
I think the date shouldn't be in the file name. It will be automatically included based on when the file was created and updated. 
## Example:
![Screen Shot 2021-08-22 at 1 35 54 PM](https://user-images.githubusercontent.com/31802656/130342480-a21d7e68-3a75-41ad-bbb3-2fadec9ed3d0.png)

2021-08-22 04:38 UTC, theyokohamalife commented on 2021.07.25.My-Cool-News-Story/en.md
> +# Hello, World
We should ask writers to include the meta data at the top of the article:

```
---
tag: News
title: Welcome to Find a Doc
description: Thanks to community efforts, thousands have been vaccinated across Japan!
author:
  name: LaShawn
  bio: Find a Doc Creator
---
```

2021-08-22 14:53 UTC, ann-kilzer commented on 2021.07.25.My-Cool-News-Story/en.md
> +# Hello, World
It's kinda helpful to have the date in the filename because they will be sorted in historical order, especially when there are many files. But I can change it if you don't want that

2021-08-22 14:53 UTC, ann-kilzer commented on .github/CODEOWNERS
> +* @theyokohamalife @ann-kilzer @Ermish
```suggestion
* @theyokohamalife @ann-kilzer @ermish
```

2021-09-08 10:31 UTC, theyokohamalife commented on 2021.07.25.My-Cool-News-Story/en.md
> +# Hello, World
@ann-kilzer Could you change the date to use dashes? It's just a personal preference. Other than that LGTM!

2021-09-08 12:52 UTC, theyokohamalife approved these changes
LGTM!

2021-09-11 08:13 UTC, merged